# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
cache: pip
env:
- FLASK_APP=autoapp.py FLASK_DEBUG=1
python:
  - 3.6
install:
  - pip install pipenv
  - pipenv install --dev
  - nvm install 8.9.1
  - nvm use 8.9.1
  - npm install
before_script:
  - npm run lint
  - npm run build
  - flask lint
script: flask test
