version: "3.7"
services:
  traefik:
    image: "traefik:v2.1.3"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --api
      - --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.le.acme.email=austin.s.mcconnell@gmail.com
      - --certificatesresolvers.le.acme.storage=/config/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .volumes/traefik/:/config
    labels:
      # Dashboard
      - traefik.http.routers.traefik.rule=Host(`traefik.docker.localhost`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls.certresolver=le
      - traefik.http.routers.traefik.entrypoints=websecure

      # global redirect to https
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https

      # middleware redirect
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/myflaskapp
      REDIS_URL: redis://redis
    volumes:
      - ./app/:/home/myflaskapp/app
      - ./migrations/:/home/myflaskapp/migrations
    labels:
      - traefik.http.routers.myflaskapp.rule=Host(`myflaskapp.docker.localhost`)
      - traefik.http.services.myflaskapp.loadbalancer.server.port=5000
      - traefik.http.routers.myflaskapp.tls.certresolver=le
      - traefik.http.routers.myflaskapp.entrypoints=websecure
  web-worker:
    build: .
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/myflaskapp
      REDIS_URL: redis://redis
    entrypoint: ["./boot-worker.sh"]
    volumes:
      - ./app/:/home/myflaskapp/app
      - ./migrations/:/home/myflaskapp/migrations
  db:
    image: postgres:12.1
    ports:
    - 15432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: myflaskapp
    volumes:
      - .volumes/db:/var/lib/postgresql/data
  redis:
    image: redis:5.0
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 16379:6379
    volumes:
      - .volumes/redis:/data
