version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
        environment:
          FLASK_APP: app.app
          FLASK_ENV: development
          SECRET_TOKEN: super-secret
          SQLALCHEMY_TEST_DATABASE_URI: postgresql://postgres:@localhost:5432/myflaskapp
      - image: postgres:11.1-alpine
        environment:
          POSTGRES_DB: myflaskapp
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install graphviz
          command: sudo apt-get install graphviz
      - restore_cache:
          key: deps1-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools
            pip install pipenv codecov
            pipenv install --dev
      - save_cache:
          key: deps1-{{ checksum "Pipfile.lock" }}
          paths:
            - "venv"
      - run:
          name: Run pre-commit checks
          command: |
            . venv/bin/activate
            flask check
      - run:
          name: Run mypy checker
          command: |
            . venv/bin/activate
            mypy app --ignore-missing-imports
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest --cov app --cov-branch --cov-report=html
      - run:
          name: Code coverage
          command: |
            . venv/bin/activate
            codecov
      - store_artifacts:
          path: htmlcov/
