version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.3
        environment:
          FLASK_CONFIG: testing
          FLASK_APP: run.py
          FLASK_DEBUG: 1
          SECRET_TOKEN: super-secret
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pipenv
            pip install codecov
            pipenv install --dev
      - save_cache:
          key: deps1-{{ checksum "Pipfile.lock" }}
          paths:
            - "venv"
      - run:
          name: Run Python linter
          command: |
            . venv/bin/activate
            flask lint
      - run:
          name: Run mypy checker
          command: |
            . venv/bin/activate
            mypy myflaskapp --ignore-missing-imports
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest --cov-report=html
      - run:
          name: Code coverage
          command: |
            . venv/bin/activate
            codecov
      - store_artifacts:
          path: htmlcov/
