version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.3
        environment:
          FLASK_APP: app.app
          FLASK_ENV: testing
          SECRET_TOKEN: super-secret
          DATABASE_USERNAME: postgres
          DATABASE_NAME: myflaskapp-test
      - image: postgres:11.1-alpine
        environment:
          POSTGRES_DB: myflaskapp-test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pipenv
            pip install codecov
            pipenv install --dev
      - save_cache:
          key: deps1-{{ checksum "Pipfile.lock" }}
          paths:
            - "venv"
      - restore_cache:
          name: Restoring Pre-Commit repositories
          key: pre-commit1000-{{ checksum ".pre-commit-config.yml" }}
      - run:
          name: Run pre-commit checks
          command: |
            . venv/bin/activate
            flask check
      - save_cache:
          name: Savings Pre-Commit repositories
          key: pre-commit1000-{{ checksum ".pre-commit-config.yml" }}
          paths:
            - /home/circleci/.cache/pre-commit
      - run:
          name: Run mypy checker
          command: |
            . venv/bin/activate
            mypy app --ignore-missing-imports
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest --cov app --cov-branch --cov-report=html
      - run:
          name: Code coverage
          command: |
            . venv/bin/activate
            codecov
      - store_artifacts:
          path: htmlcov/
