version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.3-node
        environment:
          FLASK_CONFIG: testing
          FLASK_APP: autoapp.py
          FLASK_DEBUG: 1
          SECRET_TOKEN: super-secret
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pipenv
            pipenv install --dev
      - save_cache:
          key: deps1-{{ checksum "Pipfile.lock" }}
          paths:
            - "venv"
      - restore_cache:
          key: deps1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Node dependencies
          command: npm install
      - save_cache:
          key: deps1-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Build Webpack stuff
          command: npm run build
      - run:
          name: Run Python linter
          command: |
            . venv/bin/activate
            flask lint
      - run:
          name: Run Node linter
          command: |
            . venv/bin/activate
            npm run lint
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            flask test
      - run:
          name: Code coverage
          command: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
