"""Create Tasks table.

Revision ID: 37fb54649ac2
Revises: 107f0f6ae508
Create Date: 2019-02-10 18:30:25.997565
"""
import sqlalchemy as sa
# pylint: disable=all
from alembic import op

# revision identifiers, used by Alembic.
revision = '37fb54649ac2'
down_revision = '40a38ea39210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tasks', sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=True),
        sa.Column('description', sa.String(length=128), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('complete', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tasks_user_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')))
    op.create_index(op.f('ix_tasks_name'), 'tasks', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_name'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
