"""
Add support for messages.

Revision ID: 3b87320ffdc5
Revises: 37fb54649ac2
Create Date: 2020-02-09 14:27:39.726795

"""
# pylint: disable=all
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3b87320ffdc5'
down_revision = '37fb54649ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('body', sa.String(length=140), nullable=True),
                    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'],
                                            name=op.f('fk_message_user_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
                    )
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.add_column('users',
                  sa.Column('last_message_read_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_message_read_time')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
