"""
Create Notifications table.

Revision ID: 40a38ea39210
Revises: 107f0f6ae508
Create Date: 2019-02-14 17:28:02.530420

"""
# pylint: disable=invalid-name
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '40a38ea39210'
down_revision = '107f0f6ae508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=128), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('payload', sa.JSON(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'],
                                            name=op.f('fk_notifications_user_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
                    )
    op.create_index(op.f('ix_notifications_name'), 'notifications', ['name'], unique=False)
    op.create_index(op.f('ix_notifications_timestamp'), 'notifications', ['timestamp'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_timestamp'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_name'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
