"""
Add user locale and last_seen

Revision ID: e958b6403061
Revises: 9de8b4f401a0
Create Date: 2018-10-15 07:54:56.238197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e958b6403061'
down_revision = 'c7e3b474c749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locale')
    op.drop_column('users', 'last_seen')

    # ### end Alembic commands ###
